<?php $products = $this->products; ?>
<!DOCTYPE html>
<html>
    <head>
        <link href="../style/allProducts.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <ul>
                <?php foreach ($products as $productArray): ?>
                    <li>
                        <div class="product-image"><img class="product-img" src="<?php echo $productArray[1];?>"></div>
                        <h2 class="btc"><?php echo  $productArray[2]?></h2>
                        <h3 class="dol"><?php echo $productArray[3];?> $</h3>
                        <h4><a href="products/product/<?php echo  $productArray[0]; ?>">View Product</a></h4>
                    </li>
                <?php endforeach; ?>
        </ul>
    </body>
</html>



